language: php

php:
  - 7.0

before_script:
  - mysql -e 'create database homestead;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
